openapi: 3.1.0
info:
  title: T-bank-blocking-payments-case
  version: 1.0.0
  description: API для управления блокировками платежей клиентов

components:
  schemas:
    BlockType:
      type: string
      enum: [FRAUD, INCORRECT_DETAILS, OTHER]
    BlockStatus:
      type: string
      enum: [ACTIVE, RELEASED, EXPIRED]
    BlockRequest:
      type: object
      required: [blockType]
      properties:
        blockType:
          $ref: '#/components/schemas/BlockType'
        reason:
          type: string
          maxLength: 500
        expiresAt:
          type: string
          format: date-time
    Block:
      type: object
      properties:
        id: { type: string, format: uuid }
        clientId: { type: string, format: uuid }
        type: { $ref: '#/components/schemas/BlockType' }
        status: { $ref: '#/components/schemas/BlockStatus' }
        reason: { type: string }
        createdAt: { type: string, format: date-time }
        createdBy: { type: string }
        releasedAt: { type: string, format: date-time }
        releasedBy: { type: string }
        releaseReason: { type: string }
        expiresAt: { type: string, format: date-time }
    ActiveStatus:
      type: object
      properties:
        blocked: { type: boolean }
        reason: { $ref: '#/components/schemas/BlockType' }
        blockId: { type: string, format: uuid }

paths:
  /clients/{clientId}/blocks:
    post:
      summary: Создать активную блокировку
      parameters:
        - name: clientId
          in: path
          required: true
          schema: { type: string, format: uuid }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/BlockRequest' }
      responses:
        '201':
          description: Создана блокировка
        '409':
          description: Активная блокировка уже существует

    get:
      summary: Список блокировок клиента
      parameters:
        - name: clientId
          in: path
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/Block' }
        '404':
          description: Нет пользователя с таким clientD

  /clients/{clientId}/blocks/active:
    get:
      summary: Быстрая проверка — заблокирован ли клиент сейчас
      parameters:
        - name: clientId
          in: path
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ActiveStatus' }
        '404':
          description: Нет пользователя с таким clientId

  /clients/{clientId}/blocks/{blockId}/release:
    post:
      summary: Снять блокировку
      parameters:
        - name: clientId
          in: path
          required: true
          schema: { type: string, format: uuid }
        - name: blockId
          in: path
          required: true
          schema: { type: string, format: uuid }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                  maxLength: 500
      responses:
        '200':
          description: Блокировка снята
        '404':
          description: Нет активной блокировки/нет такого пользователя
